export const DEFAULT_CATEGORY_MAP: Record<string, string> = {
  ventas: "SALES",
  sales: "SALES",
  ingresos: "SALES",
  servicios: "SERVICES",
  services: "SERVICES",
  payroll: "PAYROLL",
  nomina: "PAYROLL",
  salarios: "PAYROLL",
  tax: "TAX",
  impuestos: "TAX",
  alquiler: "RENT",
  rent: "RENT",
  suscripcion: "SUBSCRIPTION",
  subscription: "SUBSCRIPTION",
  supplier: "SUPPLIER",
  proveedor: "SUPPLIER",
  marketing: "MARKETING",
  operaciones: "OPERATIONS",
  operations: "OPERATIONS",
  capex: "CAPEX",
  inversion: "CAPEX",
  deuda: "DEBT",
  debt: "DEBT",
};
